### ISSUE TITLE
Uglify errors with jarallax

### ISSUE THREAD

**Issue by zimonline** [webpack-contrib/uglifyjs-webpack-plugin#310]
I am getting the following error when I try to uglify the following.
I don't think the problem is with jarallax as code works fine on its own.

Contents of app.js
```
import {
    jarallax,
    jarallaxElement,
    jarallaxVideo
} from 'jarallax';
```

Error
```
ERROR in /js/app.js from UglifyJs
TypeError: sym.definition is not a function
    at may_modify (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:8931:31)
    at TreeTransformer.abort [as before] (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:8541:74)
    at AST_VarDef.eval [as transform] (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
    at eval (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4586:25)
    at doit (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:130:23)
    at MAP (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:156:52)
    at do_list (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4585:16)
    at eval (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4664:28)
    at AST_Const.eval [as transform] (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4573:17)
    at collapse (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:8617:39)
    at tighten_body (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:8429:17)
    at eval (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:10529:9)
    at AST_Accessor.eval [as optimize] (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7682:23)
    at Compressor.before (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7665:24)
    at AST_Accessor.eval [as transform] (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
    at eval (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4739:33)
    at Compressor.before (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7660:9)
    at AST_ConciseMethod.eval [as transform] (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
    at eval (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4586:25)
    at doit (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:130:23)
    at MAP (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:156:52)
    at do_list (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4585:16)
    at eval (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4745:27)
    at Compressor.before (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7660:9)
    at AST_DefClass.eval [as transform] (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
    at eval (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4586:25)
    at doit (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:130:23)
    at MAP (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:156:52)
    at do_list (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4585:16)
    at eval (eval at <anonymous> (/redacted/path/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4682:25)
error An unexpected error occurred: "Command failed.
Exit code: 2
Command: sh
```

**Comment by kzc** [comment]
Resolved by #296

**Comment by kzc** [comment]
Bug workaround for `yarn` users:

https://github.com/fabiosantoscode/terser#replacing-uglify-es-with-terser-in-a-project-using-yarn

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/264

**Comment by kzc** [comment]
@evilebottnawi This bug has nothing to do with `inline` and is not addressed by #264.

It is resolved by replacing `uglify-es` with `terser` in #296.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/298
