### ISSUE TITLE
Updates 1.1.6 cause some other npm libraries errors in prod mode

### ISSUE THREAD

**Issue by vincent-cm** [webpack-contrib/uglifyjs-webpack-plugin#204]
For example the npm module ngx-progressbar 2.1.1
This node module working fine on uglifyjs-webpack-plugin <= 1.1.5

Following are the bug detail:

webpack:///./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js.pre-build-optimizer.js

this.trickling.switchMap(function () {
            return Observable
                .timer(0, _this.trickleSpeed)
                .takeWhile(function () { return _this.isStarted(); })
                .do(function () { return _this.inc(); });
        }).subscribe();

core.js.pre-build-optimizer.js:1427 ERROR TypeError: E.Observable.timer is not a function
    at t.project (ngx-progressbar.es5.js.pre-build-optimizer.js:59)
    at t._next (switchMap.js.pre-build-optimizer.js:91)
    at t.next (Subscriber.js.pre-build-optimizer.js:92)
    at t.next (Subject.js.pre-build-optimizer.js:56)
    at e.start (ngx-progressbar.es5.js.pre-build-optimizer.js:72)
    at t._next (app.component.ts:175)
    at t.__tryOrUnsub (Subscriber.js.pre-build-optimizer.js:240)
    at t.next (Subscriber.js.pre-build-optimizer.js:187)
    at t._next (Subscriber.js.pre-build-optimizer.js:128)
    at t.next (Subscriber.js.pre-build-optimizer.js:92)

**Comment by evilebottnawi** [comment]
@vincent-cm can you create minimum reproducible test repo?

**Comment by tw2as** [comment]
I am having the same problem - once uglifyjs-webpack-plugin has been updated to 1.1.6 my app became unusable when it's compiled in production mode. Compilation works fine but just after launching the app I am getting the following error

> ot.Observable.merge is not a function

which points to obfuscated code of one of my other npm packages (one of them is `@progress/kendo-angular-dropdowns@1.5.0`)

Temporarily fix is to either build it with: 

> --no-build-optimizer

or to force uglifyjs-webpack-plugin@1.1.5 by adding it to my package.json and set fixed version to 1.1.5.

uglifyjs-webpack-plugin is not in my package.json but it's used by angular-cli - angular-cli's package.json:
  
>"_id": "@angular/cli@1.6.3",
[...]
  "dependencies": {
[...]
    "uglifyjs-webpack-plugin": "^1.1.5",

If you need any more information pls let me know.

**Comment by polco** [comment]
i have some runtime errors too since the 1.1.6, but they seem to be related to the `uglify-es` update.

**Comment by evilebottnawi** [comment]
Please use `lock` file to avoid problem when uglify upgrade, sometimes some versions may contain breaking changes, i close this issue. Solution:
1. Cleanup npm cache (`npm cache clean --force`)
2. `npm install`

If you still have issue - please create issue with minimum reproducible test repo. Thanks!
