### ISSUE TITLE
undefined is not a function after upgrading from 0.4.6 to 1.0.0-beta.3

### ISSUE THREAD

**Issue by vincent-cm** [webpack-contrib/uglifyjs-webpack-plugin#138]
Uncaught TypeError: undefined is not a function
    at Array.forEach (<anonymous>)
    at :8080/main.bundle.js:214518
    at Array.forEach (<anonymous>)
    at ViewBuilder._visitElementOrTemplate (:8080/main.bundle.js:214515)
    at ViewBuilder.visitElement (:8080/main.bundle.js:214426)
    at ElementAst.visit (:8080/main.bundle.js:192104)
    at visit (:8080/main.bundle.js:192451)
    at :8080/main.bundle.js:192453
    at Array.forEach (<anonymous>)
    at templateVisitAll (:8080/main.bundle.js:192452)
    at ViewBuilder.visitAll (:8080/main.bundle.js:214273)
    at ViewCompiler.compileComponent (:8080/main.bundle.js:214174)
    at JitCompiler._compileTemplate (:8080/main.bundle.js:218950)
    at :8080/main.bundle.js:218868
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (:8080/main.bundle.js:218868)
    at :8080/main.bundle.js:218755
    at Object.then (:8080/main.bundle.js:193499)
    at JitCompiler._compileModuleAndComponents (:8080/main.bundle.js:218754)
    at JitCompiler.compileModuleAsync (:8080/main.bundle.js:218683)
    at PlatformRef_._bootstrapModuleWithZone (:8080/main.bundle.js:5553)
    at PlatformRef_.bootstrapModule (:8080/main.bundle.js:5539)
    at main (:8080/main.bundle.js:191340)
    at Object.<anonymous> (:8080/main.bundle.js:191360)
    at Object.<anonymous> (:8080/main.bundle.js:191367)
    at __webpack_require__ (:8080/main.bundle.js:708)
    at fn (:8080/main.bundle.js:113)
    at Object.defineProperty.value (:8080/main.bundle.js:191309)
    at __webpack_require__ (:8080/main.bundle.js:708)
    at Object.defineProperty.value (:8080/main.bundle.js:806)
    at :8080/main.bundle.js:809

node: 8.6.0
webpack: 3.6.0

**Comment by d3viant0ne** [comment]
There are quite a few breaking changes included in `1.0.0`. Link the repo or provide a minimal repo where this can be triaged. A stack trace isn't going to be sufficient.

In the mean time, if you have not already done so you should review the changelog: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/refactor-and-improve-cache-key/CHANGELOG.md

**Comment by nifgraup** [comment]
@d3viant0ne there is no tag for v1.0.0-beta.3, so the Changelog link for diff between .2 and .3 doesn't work.

**Comment by vincent-cm** [comment]
not a bug from this lib sorry
